version: "3"

services:
    server:
        image: gridlock:latest
        restart: always
        container_name: gridlock
        environment:
          - "LOG_FILE_DIR=/var/logs/gridlock"
          - "DOMAIN=honey.cubixle.me"
        ports:
          - "127.0.0.1:8070:8070"
        volumes: 
          - logs:/var/logs/gridlock

volumes: 
  logs:
